### ISSUE TITLE
gulp-amd-optimize vs gulp-amd-optimizer confusion

### ISSUE THREAD

**Issue by Flimm** [mariusGundersen/gulp-amd-optimizer#6]
There's a NPM module named `gulp-amd-optimizer` at the URL:

https://www.npmjs.com/package/gulp-amd-optimizer

Notice the trailing `r`. This is the published NPM package that corresponds to this repo. However, this repo GitHub URL does not have a trailing `r`, although it does use the trailing `r` in the README and in the `package.json` file.

This is confusing, because there is a different module named `gulp-amd-optimize` at the URL:

https://www.npmjs.com/package/gulp-amd-optimize

# Proposed solution:

Rename this GitHub repo to `gulp-amd-optimizer`, with a trailing `r`. If you're worried about broken links, perhaps create a new repo with the name `gulp-amd-optimize` without the trailing `r`, with a README file that simply redirects readers to the correct URL.

**Comment by mariusGundersen** [comment]
The reason it's like this is that I created this repo first, got it to work, then tried to publish it only to find that the name was already taken >_<

I'll look into renaming it, since it had probably confused lots of other people who haven't been bothered to post an issue.

**Comment by mariusGundersen** [comment]
done

**Comment by Flimm** [comment]
Thank you, that's so much clearer now :)
